### ISSUE TITLE
can't give 'ticker' arg from views.inputs to views.results

### ISSUE THREAD

**Issue by taro-kuroda-5228** [taro-kuroda-5228/django_auto_trading#9]
codes are below,
views.py
`def inputs(request):
    """This method gets ticker symbol from index.html and sends that to views.results."""

    ticker = request.POST.get("ticker")
    form = InputForm(request.POST)
    is_valid = form.is_valid()
    if is_valid:
        return HttpResponseRedirect(reverse("auto_trading:results"), args=(ticker, ))
    return HttpResponse("Alphabet only!")`

urls.py
`urlpatterns = [
    path("", views.index, name="index"),
    path("inputs/", views.inputs, name="inputs"),
    path("results/<str:ticker>", views.results, name="results")`

Error code:
Reverse for 'results' with no arguments not found. 1 pattern(s) tried: ['django_auto_trading/results/(?P<ticker>[^/]+)\\Z']

assumed reason:
can't give arg 'ticker' to views.results
Should I make /results/<str:ticker>.html file ?

**Comment by atsushimemet** [comment]
@taro-kuroda-5228 
エラーの解消方法を記載し、クローズしましょう。

**Comment by taro-kuroda-5228** [comment]
mere code error.
✕return HttpResponseRedirect(reverse("auto_trading:results"), args=(ticker, ))
〇return HttpResponseRedirect(reverse("auto_trading:results", args=(ticker, )))
args is second argument of reverse method.
